### ISSUE TITLE
NPM1 wasnt in genes of interest

### ISSUE THREAD

**Issue by ChristofferFlensburg** [annaquaglieri16/lineplots#3]
I think the excel file from Ian with the genes of interests is a bit dated, and didn't include NPM1 (and  few others, inclduing top mutated genes from tumor portal) which is one of the three genes with positive control indels.

I updated (by overwrite) the spreadsheet input_data/apotosis_genes_from_Ian.xlsx, so new analysis will include that, but might need to rerun vardict again if we want to catch the NPM1 indels... :/

I added the positive controls in a file in 06-lineplots.

**Comment by annaquaglieri16** [comment]
I see, thanks! Ok I will restart it. Shouldn't be too bad!

**Comment by annaquaglieri16** [comment]
I recreated input_data/combined_vardict_calls.rds with the new BCL2 gene list.
