### ISSUE TITLE
Interactive plots

### ISSUE THREAD

**Issue by annaquaglieri16** [annaquaglieri16/lineplots#5]
Hi Chris, 

I will give it a go because I think that at this stage this could be a more efficient way to put everything together. I will give it two days and see how it is progressing and if it is worth it. What I am thinking is the following:

An app with two/three panels

	1. Lineplots by patient: the user input will generate the usual lineplot but an interactive and dynamic plot which is linked to a table and shows more characteristics about the patient and the mutations

Example below

![screen shot 2018-11-02 at 9 38 47 am](https://user-images.githubusercontent.com/7087258/47884289-3b7e9180-de84-11e8-89cb-65f70fdc6634.png)

![screen shot 2018-11-02 at 9 41 13 am](https://user-images.githubusercontent.com/7087258/47884297-43d6cc80-de84-11e8-954f-e42d3a867385.png)

2. Hetmap panel, same as above but with the heatmap

3. Plots by mutation, depending on the time. Connect two plots, one showing the overall frequency of one mutation in the cohort and the other one showing the behaviour of that mutation across patients. 

This is what I mean

![screen shot 2018-11-02 at 9 43 22 am](https://user-images.githubusercontent.com/7087258/47884333-6ff24d80-de84-11e8-989c-0f05dcd4a51a.png)

I have done similar things before, so the main things would be to have the data in the right format which we sort of have. 

Let me know if there is something more urgent and I will help you. However, this will kind of give the freedom to Ian to explore it + it will help with the overcrowded plots because you can filter or highlight things on the plot and it will help linking the dots to more information into a table. 

Anna

**Comment by ChristofferFlensburg** [comment]
This looks super cool!

**Comment by ChristofferFlensburg** [comment]
It's super cool! :D

Let's talk more tomorrow? What time is good? We have lab meeting 3:30-4.30,
otherwise free.

**Comment by annaquaglieri16** [comment]
Thanks! What about 2.30?

**Comment by ChristofferFlensburg** [comment]
Wait, I replied to the email without realising it'd turn into a reply for the guthub page. :D
I'll send normal email next time! Let's do 2.30pm.
